import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import Header from "../components/Header";
import Login from "../components/Login";

export default function Home() {
  const { data: session } = useSession();
  if (!session) {
    return <Login />;
  } else {
    return (
      <div className="">
        <Head>
          <title>first next app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
      </div>
    );
  }
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
